events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name berlin.transitradar.de;

        root /usr/share/nginx/html;

        location = /status {
            return 301 https://status.transitradar.de/;
        }

        location = /status.html {
            return 301 https://status.transitradar.de/;
        }

        location = / {
            try_files /berlin-v2.html =404;
        }

        location = /index {
            return 301 /;
        }

        location = /index.html {
            return 301 /;
        }

        location ~ ^/(.+)\.html$ {
            return 301 /$1;
        }

        location / {
            try_files $uri $uri/ $uri.html =404;
        }
    }

    server {
        listen 80;
        server_name status.transitradar.de;

        root /usr/share/nginx/html;

        location = / {
            try_files /status.html =404;
        }

        location = /status {
            return 301 /;
        }

        location = /status.html {
            return 301 /;
        }

        location ~ ^/(.+)\.html$ {
            return 301 /$1;
        }

        location / {
            try_files $uri $uri/ $uri.html =404;
        }
    }

    server {
        listen 80 default_server;
        server_name _;

        root /usr/share/nginx/html;

        location = /status {
            return 301 https://status.transitradar.de/;
        }

        location = /status.html {
            return 301 https://status.transitradar.de/;
        }

        location = / {
            try_files /index.html =404;
        }

        location = /index {
            return 301 /;
        }

        location = /index.html {
            return 301 /;
        }

        location ~ ^/(.+)\.html$ {
            return 301 /$1;
        }

        location / {
            try_files $uri $uri/ $uri.html =404;
        }
    }
}
