events {}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name _;

        root /usr/share/nginx/html;
        index index.html;

        location = /index {
            return 301 /;
        }

        location = /index.html {
            return 301 /;
        }

        location ~ ^/(.+)\.html$ {
            return 301 /$1;
        }

        location / {
            try_files $uri $uri/ $uri.html =404;
        }
    }
}
